package com.lion.skiresortbackend.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Represent a single ski resort.
 * @author lion
 *
 */
@DynamoDBTable(tableName = "Resort")
public class Resort {
	
	private String resortId;
	
	private String resortName;
	
	public Resort() {
	}
	
	public Resort(String resortName) {
		super();
		this.resortName = resortName;
	}
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getResortId() {
		return resortId;
	}
	
	@DynamoDBAttribute
	public String getResortName() {
		return resortName;
	}
	
	public void setResortName(String resortName) {
		this.resortName = resortName;
	}
	public void setResortId(String resortId) {
		this.resortId = resortId;
	}
	
	
}
