package com.lion.skiresortbackend.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Season")
public class Season {

	private String id;
	
	private int season;
	
	private String resortId;

	public Season() {
		super();
	}

	public Season(int season, String resortId) {
		super();
		this.season = season;
		this.resortId = resortId;
	}

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	@DynamoDBAttribute
	public String getResortId() {
		return resortId;
	}

	@DynamoDBAttribute
	public int getSeason() {
		return season;
	}

	public void setId(String id) {
		this.id = id;
	}

	public void setResortId(String resortId) {
		this.resortId = resortId;
	}

	public void setSeason(int season) {
		this.season = season;
	}
	

}
